eslint:
  image: node
  script:
    - cd client
    - npm i eslint
    - npm run lint

pylint:
  image: "python:3.8"
  before_script:
    - python --version
    - pip install pylint
    - pip install flask
    - pip install pytest
  script:
    - cd client/
    - pylint server.py
    - pylint ../test_server.py

pytest:
  image: "python:3.8"
  before_script:
    - python --version
    - pip install pytest
    - pip install flask
  script:
    pytest test_server.py -v

deploy-prod:
  stage: deploy
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd CIS3760/Prod"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "git pull"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd client"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "npm run build"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "sudo rm -r /var/www/131.104.49.100/static"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "mv -v build/* /var/www/131.104.49.100/"
  environment: production
