eslint:
  image: node
  script:
    - cd client
    - npm i eslint
    - npm run lint

pylint:
  image: "python:3.8"
  before_script:
    - python --version
    - pip install pylint
    - pip install flask
    - pip install pytest
  script:
    - cd client/
    - pylint server.py
    - pylint ../test_server.py

pytest:
  image: "python:3.8"
  before_script:
    - python --version
    - pip install pytest
    - pip install flask
  script:
    pytest test_server.py -v

deploy-prod:
  stage: deploy
  tags:
    - deployment
  script:
    - pwd
    - cd /home/socs/CIS3760/Prod
    - git pull && rfarre04
    - cd client
    - ip addr
    - npm run build
    - sudo rm -r /var/www/131.104.49.100/static
    - mv -v build/* /var/www/131.104.49.100/
  environment: production
